<?php

namespace Database\Seeders;

use App\Models\User;
// use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     */
    public function run()
    {
        // User::factory(10)->create();

        DB::table('categories')->insert([
            [
                'name' => 'Chips',
                'slug' => Str::slug('Chips'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Chocolates',
                'slug' => Str::slug('Chocolates'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Drinks',
                'slug' => Str::slug('Drinks'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nuts',
                'slug' => Str::slug('Nuts'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Biscuits',
                'slug' => Str::slug('Biscuits'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fruit Snacks',
                'slug' => Str::slug('Fruit Snacks'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Candy',
                'slug' => Str::slug('Candy'),
                'admin_id' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);

        $products = [
            // ------------------ CHIPS ------------------
            [
                'name' => 'Spicy Tomato Chips',
                'slug' => Str::slug('Spicy Tomato Chips'),
                'price' => 2.99,
                'amount_value' => 150,
                'amount_unit' => 'g',
                'country_origin' => 'Mexico',
                'image' => 'https://images.unsplash.com/photo-1633536705882-d331e8d1858c',
                'ingredients' => 'Potatoes, Vegetable Oil, Tomato Powder, Salt, Spices',
                'nutritional_info' => '540 kcal/100g, Fat: 32g, Carbs: 50g, Protein: 6g',
                'storage_conditions' => 'Store in a cool, dry place',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'Sea Salt Kettle Chips',
                'slug' => Str::slug('Sea Salt Kettle Chips'),
                'price' => 3.20,
                'amount_value' => 200,
                'amount_unit' => 'g',
                'country_origin' => 'UK',
                'image' => 'https://images.unsplash.com/photo-1511690743698-d9d85f2fbf38',
                'ingredients' => 'Potatoes, Sunflower Oil, Sea Salt',
                'nutritional_info' => '520 kcal/100g, Fat: 28g, Carbs: 52g, Protein: 7g',
                'storage_conditions' => 'Keep sealed for freshness',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 1,
                'category_id' => 1,
            ],
            [
                'name' => 'Sour Cream & Onion Chips',
                'slug' => Str::slug('Sour Cream Onion Chips'),
                'price' => 2.75,
                'amount_value' => 140,
                'amount_unit' => 'g',
                'country_origin' => 'USA',
                'image' => 'https://images.unsplash.com/photo-1585238341986-df1f1f7c9f56',
                'ingredients' => 'Potatoes, Onion Powder, Sour Cream Flavor, Salt',
                'nutritional_info' => '550 kcal/100g, Fat: 30g, Carbs: 55g, Protein: 6g',
                'storage_conditions' => 'Store in dry place',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 1,
                'category_id' => 1,
            ],

            // ------------------ CHOCOLATES ------------------
            [
                'name' => 'Belgian Dark Chocolate Bar',
                'slug' => Str::slug('Belgian Dark Chocolate Bar'),
                'price' => 4.50,
                'amount_value' => 100,
                'amount_unit' => 'g',
                'country_origin' => 'Belgium',
                'image' => 'https://images.unsplash.com/photo-1702743692629-b11e94c63b0a',
                'ingredients' => 'Cocoa Mass, Cocoa Butter, Sugar',
                'nutritional_info' => '560 kcal/100g, Fat: 40g, Carbs: 35g, Protein: 7g',
                'storage_conditions' => 'Keep cool and dry',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 2,
                'category_id' => 2,
            ],
            [
                'name' => 'Swiss Milk Chocolate',
                'slug' => Str::slug('Swiss Milk Chocolate'),
                'price' => 3.80,
                'amount_value' => 120,
                'amount_unit' => 'g',
                'country_origin' => 'Switzerland',
                'image' => 'https://images.unsplash.com/photo-1599785209707-28adf6b9e6ad',
                'ingredients' => 'Milk Powder, Cocoa Butter, Cocoa Mass, Sugar',
                'nutritional_info' => '580 kcal/100g, Fat: 38g, Carbs: 52g, Protein: 8g',
                'storage_conditions' => 'Store in cool, dry area',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 2,
                'category_id' => 2,
            ],
            [
                'name' => 'Hazelnut Chocolate Bar',
                'slug' => Str::slug('Hazelnut Chocolate Bar'),
                'price' => 5.10,
                'amount_value' => 90,
                'amount_unit' => 'g',
                'country_origin' => 'Italy',
                'image' => 'https://images.unsplash.com/photo-1542327897-414e3e4439a4',
                'ingredients' => 'Hazelnuts, Cocoa Mass, Sugar, Cocoa Butter',
                'nutritional_info' => '600 kcal/100g, Fat: 42g, Carbs: 40g, Protein: 9g',
                'storage_conditions' => 'Keep in dry place below 20°C',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 2,
                'category_id' => 2,
            ],

            // ------------------ DRINKS ------------------
            [
                'name' => 'Mango Sparkling Drink',
                'slug' => Str::slug('Mango Sparkling Drink'),
                'price' => 1.99,
                'amount_value' => 330,
                'amount_unit' => 'ml',
                'country_origin' => 'Japan',
                'image' => 'https://images.unsplash.com/photo-1634825881542-9bd54ca437ea',
                'ingredients' => 'Carbonated Water, Sugar, Mango Flavoring',
                'nutritional_info' => '150 kcal per can, Sugar: 35g',
                'storage_conditions' => 'Serve chilled',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 3,
                'category_id' => 3,
            ],
            [
                'name' => 'Lychee Iced Tea',
                'slug' => Str::slug('Lychee Iced Tea'),
                'price' => 2.50,
                'amount_value' => 500,
                'amount_unit' => 'ml',
                'country_origin' => 'Thailand',
                'image' => 'https://images.unsplash.com/photo-1617196038434-66b5a6e5cb65',
                'ingredients' => 'Black Tea, Lychee Extract, Sugar',
                'nutritional_info' => '120 kcal per bottle, Sugar: 28g',
                'storage_conditions' => 'Best served cold',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 3,
                'category_id' => 3,
            ],
            [
                'name' => 'Coconut Water',
                'slug' => Str::slug('Coconut Water'),
                'price' => 2.20,
                'amount_value' => 330,
                'amount_unit' => 'ml',
                'country_origin' => 'Philippines',
                'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf',
                'ingredients' => '100% Coconut Water',
                'nutritional_info' => '60 kcal per can, Potassium: 400mg',
                'storage_conditions' => 'Keep refrigerated after opening',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 3,
                'category_id' => 3,
            ],

            // ------------------ NUTS ------------------
            [
                'name' => 'Roasted Almond Mix',
                'slug' => Str::slug('Roasted Almond Mix'),
                'price' => 5.25,
                'amount_value' => 200,
                'amount_unit' => 'g',
                'country_origin' => 'USA',
                'image' => 'https://images.unsplash.com/photo-1671981200629-014c03829abb',
                'ingredients' => 'Almonds, Cashews, Hazelnuts, Sea Salt',
                'nutritional_info' => '620 kcal/100g, Fat: 55g, Carbs: 18g, Protein: 20g',
                'storage_conditions' => 'Keep airtight',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 4,
                'category_id' => 4,
            ],
            [
                'name' => 'Honey Roasted Peanuts',
                'slug' => Str::slug('Honey Roasted Peanuts'),
                'price' => 3.80,
                'amount_value' => 180,
                'amount_unit' => 'g',
                'country_origin' => 'Canada',
                'image' => 'https://images.unsplash.com/photo-1621682375800-0c9c4f5f7b4d',
                'ingredients' => 'Peanuts, Honey, Sugar, Salt',
                'nutritional_info' => '580 kcal/100g, Fat: 48g, Carbs: 22g, Protein: 19g',
                'storage_conditions' => 'Store in cool, dry place',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 4,
                'category_id' => 4,
            ],
            [
                'name' => 'Pistachio Kernels',
                'slug' => Str::slug('Pistachio Kernels'),
                'price' => 6.90,
                'amount_value' => 150,
                'amount_unit' => 'g',
                'country_origin' => 'Iran',
                'image' => 'https://images.unsplash.com/photo-1628760220361-dce49963cf14',
                'ingredients' => 'Pistachios, Salt',
                'nutritional_info' => '630 kcal/100g, Fat: 54g, Carbs: 20g, Protein: 21g',
                'storage_conditions' => 'Keep sealed',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 4,
                'category_id' => 4,
            ],

            // ------------------ BISCUITS ------------------
            [
                'name' => 'Butter Cookies',
                'slug' => Str::slug('Butter Cookies'),
                'price' => 3.20,
                'amount_value' => 250,
                'amount_unit' => 'g',
                'country_origin' => 'Denmark',
                'image' => 'https://images.unsplash.com/photo-1657021717831-73211ff92daf',
                'ingredients' => 'Wheat Flour, Butter, Sugar, Eggs',
                'nutritional_info' => '510 kcal/100g, Fat: 26g, Carbs: 60g, Protein: 5g',
                'storage_conditions' => 'Keep dry',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 5,
                'category_id' => 5,
            ],
            [
                'name' => 'Chocolate Chip Cookies',
                'slug' => Str::slug('Chocolate Chip Cookies'),
                'price' => 2.80,
                'amount_value' => 200,
                'amount_unit' => 'g',
                'country_origin' => 'USA',
                'image' => 'https://images.unsplash.com/photo-1599785209707-28adf6b9e6ad',
                'ingredients' => 'Wheat Flour, Chocolate Chips, Butter, Sugar, Eggs',
                'nutritional_info' => '520 kcal/100g, Fat: 24g, Carbs: 62g, Protein: 6g',
                'storage_conditions' => 'Store in airtight jar',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 5,
                'category_id' => 5,
            ],
            [
                'name' => 'Matcha Biscuits',
                'slug' => Str::slug('Matcha Biscuits'),
                'price' => 3.90,
                'amount_value' => 150,
                'amount_unit' => 'g',
                'country_origin' => 'Japan',
                'image' => 'https://images.unsplash.com/photo-1585238341986-df1f1f7c9f56',
                'ingredients' => 'Wheat Flour, Sugar, Butter, Matcha Powder',
                'nutritional_info' => '500 kcal/100g, Fat: 22g, Carbs: 65g, Protein: 5g',
                'storage_conditions' => 'Store in cool, dry place',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 5,
                'category_id' => 5,
            ],

            // ------------------ FRUIT SNACKS ------------------
            [
                'name' => 'Strawberry Fruit Gummies',
                'slug' => Str::slug('Strawberry Fruit Gummies'),
                'price' => 2.10,
                'amount_value' => 120,
                'amount_unit' => 'g',
                'country_origin' => 'Germany',
                'image' => 'https://images.unsplash.com/photo-1599738675654-125cf46f3b69',
                'ingredients' => 'Glucose Syrup, Sugar, Gelatin, Strawberry Juice',
                'nutritional_info' => '350 kcal/100g, Sugar: 70g',
                'storage_conditions' => 'Keep sealed',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 6,
                'category_id' => 6,
            ],
            [
                'name' => 'Mango Fruit Leather',
                'slug' => Str::slug('Mango Fruit Leather'),
                'price' => 2.60,
                'amount_value' => 100,
                'amount_unit' => 'g',
                'country_origin' => 'India',
                'image' => 'https://images.unsplash.com/photo-1585238341986-df1f1f7c9f56',
                'ingredients' => 'Mango Puree, Sugar, Citric Acid',
                'nutritional_info' => '320 kcal/100g, Carbs: 80g',
                'storage_conditions' => 'Store dry',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 6,
                'category_id' => 6,
            ],
            [
                'name' => 'Apple Rings',
                'slug' => Str::slug('Apple Rings'),
                'price' => 3.30,
                'amount_value' => 150,
                'amount_unit' => 'g',
                'country_origin' => 'Poland',
                'image' => 'https://images.unsplash.com/photo-1542327897-414e3e4439a4',
                'ingredients' => 'Dried Apple Slices, Sulphur Dioxide (Preservative)',
                'nutritional_info' => '280 kcal/100g, Fiber: 8g',
                'storage_conditions' => 'Keep sealed, away from moisture',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 6,
                'category_id' => 6,
            ],

            // ------------------ CANDY ------------------
            [
                'name' => 'Rainbow Candy Mix',
                'slug' => Str::slug('Rainbow Candy Mix'),
                'price' => 3.75,
                'amount_value' => 180,
                'amount_unit' => 'g',
                'country_origin' => 'UK',
                'image' => 'https://images.unsplash.com/photo-1476401113995-b136bdfce591',
                'ingredients' => 'Sugar, Glucose Syrup, Food Coloring, Flavors',
                'nutritional_info' => '400 kcal/100g, Sugar: 85g',
                'storage_conditions' => 'Store cool & dry',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 7,
                'category_id' => 7,
            ],
            [
                'name' => 'Caramel Toffees',
                'slug' => Str::slug('Caramel Toffees'),
                'price' => 2.50,
                'amount_value' => 160,
                'amount_unit' => 'g',
                'country_origin' => 'France',
                'image' => 'https://images.unsplash.com/photo-1628760220361-dce49963cf14',
                'ingredients' => 'Sugar, Butter, Cream, Glucose Syrup',
                'nutritional_info' => '420 kcal/100g, Fat: 14g, Sugar: 72g',
                'storage_conditions' => 'Keep airtight, away from heat',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 7,
                'category_id' => 7,
            ],
            [
                'name' => 'Sour Gummy Worms',
                'slug' => Str::slug('Sour Gummy Worms'),
                'price' => 2.20,
                'amount_value' => 150,
                'amount_unit' => 'g',
                'country_origin' => 'USA',
                'image' => 'https://images.unsplash.com/photo-1600880292203-757bb62b4baf',
                'ingredients' => 'Sugar, Gelatin, Citric Acid, Fruit Flavor',
                'nutritional_info' => '390 kcal/100g, Sugar: 82g',
                'storage_conditions' => 'Store in a dry place',
                'is_mystery_box' => 0,
                'admin_id' => 1,
                'brand_id' => 7,
                'category_id' => 7,
            ],
        ];

        DB::table('products')->insert($products);
    }
}
